a= int(input("Enter the first value"))
b= int(input("Enter the second value"))
print("a+b",  a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a/b", a/b)
print("a%b", a%b)
print("a**b", a**b)
print("a//b", a//b)
